{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-24659",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://gitlab.com/gnutls/gnutls/-/issues/1071",
                    "name": "https://gitlab.com/gnutls/gnutls/-/issues/1071",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https://security.gentoo.org/glsa/202009-01",
                    "name": "GLSA-202009-01",
                    "refsource": "GENTOO",
                    "tags": []
                },
                {
                    "url": "https://www.gnutls.org/security-new.html#GNUTLS-SA-2020-09-04",
                    "name": "https://www.gnutls.org/security-new.html#GNUTLS-SA-2020-09-04",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "An issue was discovered in GnuTLS before 3.6.15. A server can trigger a NULL pointer dereference in a TLS 1.3 client if a no_renegotiation alert is sent with unexpected timing, and then an invalid second handshake occurs. The crash happens in the application's error handling path, where the gnutls_deinit function is called after detecting a handshake failure."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-09-04T15:15Z",
    "lastModifiedDate": "2020-09-06T02:15Z"
}