{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-24372",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://github.com/LuaJIT/LuaJIT/issues/603",
                    "name": "https://github.com/LuaJIT/LuaJIT/issues/603",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "LuaJIT through 2.1.0-beta3 has an out-of-bounds read in lj_err_run in lj_err.c."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-08-17T17:15Z",
    "lastModifiedDate": "2020-08-17T17:15Z"
}