{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-24342",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "http://lua-users.org/lists/lua-l/2020-07/msg00052.html",
                    "name": "http://lua-users.org/lists/lua-l/2020-07/msg00052.html",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https://github.com/lua/lua/commit/34affe7a63fc5d842580a9f23616d057e17dfe27",
                    "name": "https://github.com/lua/lua/commit/34affe7a63fc5d842580a9f23616d057e17dfe27",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "Lua through 5.4.0 allows a stack redzone cross in luaO_pushvfstring because a protection mechanism wrongly calls luaD_callnoyield twice in a row."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-08-13T19:15Z",
    "lastModifiedDate": "2020-08-13T19:50Z"
}