{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2013-7489",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1850105",
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1850105",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https://github.com/bbangert/beaker/issues/191",
                    "name": "https://github.com/bbangert/beaker/issues/191",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https://www.openwall.com/lists/oss-security/2020/05/14/11",
                    "name": "https://www.openwall.com/lists/oss-security/2020/05/14/11",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "The Beaker library through 1.11.0 for Python is affected by deserialization of untrusted data, which could lead to arbitrary code execution."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-06-26T20:15Z",
    "lastModifiedDate": "2020-06-26T20:31Z"
}