{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-14162",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://0xpanic.github.io/2020/07/21/Pihole.html",
                    "name": "https://0xpanic.github.io/2020/07/21/Pihole.html",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https://docs.pi-hole.net/core/pihole-command/",
                    "name": "https://docs.pi-hole.net/core/pihole-command/",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "An issue was discovered in Pi-Hole through 5.0. The local www-data user has sudo privileges to execute the pihole core script as root without a password, which could allow an attacker to obtain root access via shell metacharacters to this script's setdns command."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-07-30T14:15Z",
    "lastModifiedDate": "2020-07-30T15:24Z"
}