{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-14332",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-14332",
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-14332",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https://github.com/ansible/ansible/pull/71033",
                    "name": "https://github.com/ansible/ansible/pull/71033",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "A flaw was found in the Ansible Engine when using module_args. Tasks executed with check mode (--check-mode) do not properly neutralize sensitive data exposed in the event data. This flaw allows unauthorized users to read this data. The highest threat from this vulnerability is to confidentiality."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-09-11T18:15Z",
    "lastModifiedDate": "2020-09-11T18:15Z"
}